stages:
  - test
  - build

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_ROOT: "/sdk"

before_script:
  - export PATH=$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools
  - chmod +x ./gradlew

test_job:
  stage: test
  image: gradle:8.4.0-jdk17
  script:
    - ./gradlew test

build_job:
  stage: build
  image: gradle:8.4.0-jdk17
  script:
    - ./gradlew assembleDebug
